"""
PySpark Code Generator - assembles the final .py file from converted components.
Follows Steps 3-5 of the 7-step AI Framework Pipeline.
"""
 
import re
import textwrap
from datetime import date
from converter.sql_parser import ParsedSQL
from converter.sql_analyzer import AnalysisReport
from converter import sql_converter as CV
from sql_mappings.sql_types import resolve_type
# Regex to find the last DataFrame variable assigned in generated body
_DF_VAR_RE = re.compile(r'^\s*(\w+_df)\s*[=\.]', re.MULTILINE)
 
# ------------------------------------------------------------------------------
#  Standard imports block
# ------------------------------------------------------------------------------
 
_BASE_IMPORTS = """\
import os
import sys
import logging
from typing import Optional, List, Any

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql import types as T
from pyspark.sql.types import (
    StructType, StructField,
    IntegerType, LongType, StringType, DoubleType, FloatType,
    DecimalType, BooleanType, DateType, TimestampType, BinaryType,
    ArrayType, MapType,
)
from pyspark.sql.window import Window

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)
"""
 
_DELTA_IMPORT = "from delta.tables import DeltaTable"
 
_SPARK_LOCAL = """\
# =============================================================================
# SPARK SESSION
# On Databricks: 'spark' is already available - delete this block.
# Locally (VS Code / pytest): creates a local session with Delta support.
# =============================================================================
def get_spark() -> SparkSession:
    return (
        SparkSession.builder
        .appName("SQL_to_PySpark_Converter")
        .config("spark.sql.extensions",
                "io.delta.sql.DeltaSparkSessionExtension")
        .config("spark.sql.catalog.spark_catalog",
                "org.apache.spark.sql.delta.catalog.DeltaCatalog")
        .config("spark.sql.adaptive.enabled", "true")
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
        .master("local[*]")
        .getOrCreate()
    )

if "spark" not in dir():
    spark = get_spark()
    spark.sparkContext.setLogLevel("WARN")
"""
 
 
class PySparkGenerator:
    """
    Orchestrates the full conversion pipeline and writes a .py file.
    """
 
    def __init__(self, db_prefix: str = ""):
        self.db_prefix = db_prefix
 
    # -- public ----------------------------------------------------------------
 
    def generate(self, parsed: ParsedSQL, report: AnalysisReport) -> str:
        """Return the full PySpark Python source as a string."""
        sections: list[str] = []

        sections.append(self._file_header(parsed, report))
        sections.append(_BASE_IMPORTS)

        if self._needs_delta(parsed):
            sections.append(_DELTA_IMPORT + "\n")

        sections.append(_SPARK_LOCAL)
        sections.append(self._function_def(parsed, report))
        sections.append(self._invocation_example(parsed))
        sections.append(self._validation_scaffold(parsed))
        return "\n\n".join(s.rstrip() for s in sections if s.strip())

    # -- private sections ------------------------------------------------------

    @staticmethod
    def _file_header(parsed: ParsedSQL, report: AnalysisReport) -> str:
        name = parsed.sp_name or "sql_query"
        warnings_txt = ""
        if report.conversion_warnings:
            warnings_txt = "\n# CONVERSION WARNINGS:\n"
            for w in report.conversion_warnings:
                warnings_txt += f"#   ⚠  {w}\n"
        return (
            f'"""\n'
            f"PySpark Equivalent: {name}\n"
            f"Generated by SQL-to-PySpark AI Framework\n"
            f"Date: {date.today().isoformat()}\n"
            f"Complexity Score: {report.complexity_score}/10\n"
            f"Source Type: {'Stored Procedure' if parsed.is_stored_procedure else 'SQL Query'}\n"
            f'"""\n'
            f"# {'='*70}\n"
            f"# CONVERSION SUMMARY\n"
            f"# {'='*70}\n"
            f"# Parameters       : {len(parsed.parameters)}\n"
            f"# Temp Tables      : {len(parsed.temp_tables)} "
            f"({', '.join(t.name for t in parsed.temp_tables) or 'none'})\n"
            f"# Table Deps       : {', '.join(report.dependencies) or 'none'}\n"
            f"# Has Cursors      : {report.has_cursors}\n"
            f"# Has Transactions : {report.has_transactions}\n"
            f"# Has Dynamic SQL  : {report.has_dynamic_sql}\n"
            f"# Has Window Funcs : {report.has_window_functions}\n"
            f"# CTE Patterns     : {', '.join(report.cte_patterns) or 'none'}\n"
            + warnings_txt
        )
 
    def _function_def(self, parsed: ParsedSQL, report: AnalysisReport) -> str:
        """Build the main Python function."""
        fn_name  = self._to_fn_name(parsed.sp_name) if parsed.sp_name else "run_query"
        py_args  = CV.convert_parameters(parsed.parameters)
        sig_args = ["spark: SparkSession"] + py_args
        sig      = f"def {fn_name}(\n    " + ",\n    ".join(sig_args) + "\n):"
 
        body_lines: list[str] = []
 
        # Docstring
        body_lines.append(f'    """')
        body_lines.append(f'    PySpark conversion of: {parsed.sp_name or "SQL Query"}')
        if parsed.parameters:
            body_lines.append(f'    Args:')
            body_lines.append(f'        spark: Active SparkSession')
            for p in parsed.parameters:
                py_nm = CV._clean_name(p.name)
                default_note = f" (default: {p.default})" if p.default else ""
                body_lines.append(f'        {py_nm}: {p.sql_type}{default_note}')
        body_lines.append(f'    Returns:')
        body_lines.append(f'        DataFrame with query results')
        body_lines.append(f'    """')
 
        # DECLARE variables
        if parsed.variables:
            body_lines.append("")
            body_lines.append("    # -- Python variables (from SQL DECLARE) -------------")
            for var in parsed.variables:
                body_lines.append(f"    {CV.convert_declare(var)}")
 
        # Convert each statement
        body_lines.append("")
        body_lines.append("    # -- Main logic ------------------------------------------")
 
        cursor_names = set(report.cursor_patterns)
        all_converted_blocks: list[str] = []
 
        # Build a combined cursor context map: cursor_name ? DECLARE raw SQL
        # so that when the WHILE @@FETCH_STATUS block is reached, we can pass
        # the full cursor context (DECLARE + WHILE) to convert_cursor().
        cursor_declare_map: dict[str, str] = {}
        for stmt in parsed.statements:
            if stmt.stmt_type == "DECLARE" and re.search(r"\bCURSOR\b", stmt.raw_sql, re.IGNORECASE):
                m = re.search(r"DECLARE\s+([\w]+)\s+CURSOR", stmt.raw_sql, re.IGNORECASE)
                if m:
                    cursor_declare_map[m.group(1).upper()] = stmt.raw_sql

        for stmt in parsed.statements:
            converted = self._convert_one_statement(
                stmt, cursor_names, cursor_declare_map
            )
            if converted:
                all_converted_blocks.append(converted)
                for line in converted.split("\n"):
                    body_lines.append(f"    {line}")
                body_lines.append("")
 
        # Detect the last DataFrame variable produced in the generated code
        full_body = "\n".join(all_converted_blocks)
        df_matches = _DF_VAR_RE.findall(full_body)
        # Pick the last _df variable that was assigned (not just accessed)
        last_df_var = df_matches[-1] if df_matches else None
 
        if last_df_var:
            body_lines.append(f"    return {last_df_var}")
        elif all_converted_blocks:
            body_lines.append(
                "    # NOTE: Add your DataFrame return variable above\n"
                "    # e.g.:  return result_df"
            )
        else:
            # Absolutely nothing was generated � wrap entire raw body as spark.sql()
            raw_clean = parsed.raw_body.strip().rstrip(";")
            body_lines.append("    # NOTE: Input could not be parsed � using full spark.sql() passthrough")
            body_lines.append(f'    result_df = spark.sql("""')
            for line in raw_clean.split("\n"):
                body_lines.append(f"        {line}")
            body_lines.append('    """)')
            body_lines.append("    result_df.show()")
            body_lines.append("    return result_df")
 
        return sig + "\n" + "\n".join(body_lines)
 
    def _convert_one_statement(self, stmt, cursor_names: set, cursor_declare_map: dict = None) -> str:
        t = stmt.stmt_type
        raw = stmt.raw_sql.strip()
        if cursor_declare_map is None:
            cursor_declare_map = {}

        # -- Cursor lifecycle statements � suppress or comment ----------------
        # OPEN / FETCH (standalone) / CLOSE / DEALLOCATE have no PySpark equivalent;
        # the actual conversion is generated by the WHILE @@FETCH_STATUS block below.
        if re.search(r"^\s*OPEN\s+\w+", raw, re.IGNORECASE):
            cursor_m = re.search(r"OPEN\s+([\w]+)", raw, re.IGNORECASE)
            cname = cursor_m.group(1) if cursor_m else "cursor"
            return f"# OPEN {cname} ? handled by spark.sql() in DataFrame load above"

        if re.search(r"^\s*CLOSE\s+\w+", raw, re.IGNORECASE):
            cursor_m = re.search(r"CLOSE\s+([\w]+)", raw, re.IGNORECASE)
            cname = cursor_m.group(1) if cursor_m else "cursor"
            return f"# CLOSE {cname} ? no-op in PySpark (DataFrame released at function end)"

        if re.search(r"^\s*DEALLOCATE\s+\w+", raw, re.IGNORECASE):
            cursor_m = re.search(r"DEALLOCATE\s+([\w]+)", raw, re.IGNORECASE)
            cname = cursor_m.group(1) if cursor_m else "cursor"
            return f"# DEALLOCATE {cname} ? no-op in PySpark"

        # Standalone FETCH NEXT (outside WHILE) � skip, handled in foreachPartition
        if re.search(r"^\s*FETCH\s+NEXT\s+FROM", raw, re.IGNORECASE):
            return "# FETCH NEXT ? handled within foreachPartition body above"

        if t == "SELECT":
            return CV.convert_select(stmt, self.db_prefix)
        elif t == "INSERT":
            return CV.convert_insert(stmt, self.db_prefix)
        elif t == "UPDATE":
            return CV.convert_update(stmt, self.db_prefix)
        elif t == "DELETE":
            return CV.convert_delete(stmt, self.db_prefix)
        elif t == "MERGE":
            return CV.convert_merge(stmt, self.db_prefix)
        elif t == "IF":
            return CV.convert_if_else(stmt)
        elif t == "WHILE":
            # Cursor WHILE @@FETCH_STATUS � combine DECLARE context + WHILE body
            if re.search(r"@@FETCH_STATUS|FETCH\s+NEXT", raw, re.IGNORECASE):
                fetch_m = re.search(r"FETCH\s+NEXT\s+FROM\s+([\w]+)", raw, re.IGNORECASE)
                cursor_key = fetch_m.group(1).upper() if fetch_m else ""
                declare_sql = cursor_declare_map.get(cursor_key, "")
                # Combine DECLARE (has FOR SELECT) + WHILE (has body) ? full context
                combined = (declare_sql + "\n" + raw).strip() if declare_sql else raw
                return CV.convert_cursor(combined)
            return CV.convert_while(stmt)
        elif t == "DECLARE":
            if re.search(r"\bCURSOR\b", raw, re.IGNORECASE):
                # Only emit a stub � the full conversion comes from the WHILE block
                cursor_m = re.search(r"DECLARE\s+([\w]+)\s+CURSOR", raw, re.IGNORECASE)
                cname = cursor_m.group(1) if cursor_m else "cursor"
                return (
                    f"# DECLARE CURSOR '{cname}' ? converted below in the "
                    f"WHILE @@FETCH_STATUS block (foreachPartition / DeltaTable.merge)"
                )
            # Regular variable DECLARE already handled via parsed.variables
            return ""
        elif t == "SET":
            return CV.convert_set_statement(raw)
        elif t == "CREATE_TABLE":
            return CV.convert_create_temp(stmt)
        elif t == "DROP_TABLE":
            return CV.convert_drop_temp(stmt)
        elif t == "PRINT":
            return CV.convert_print(stmt)
        elif t == "EXEC":
            return CV.convert_exec(stmt)
        elif t in ("BEGIN_BLOCK", "END_BLOCK"):
            return ""
        elif t == "OTHER":
            # Anything unrecognised ? passthrough as spark.sql()
            return CV.convert_unknown(stmt)
        elif t == "CTE":
            # Passthrough as spark.sql()
            clean = raw.rstrip(";")
            return (
                f"# CTE (WITH clause) � passthrough as spark.sql()\n"
                f'result_df = spark.sql("""\n    {clean}\n""")'
            )
        else:
            if raw:
                return CV.convert_unknown(stmt)
            return ""
 
    @staticmethod
    def _invocation_example(parsed: ParsedSQL) -> str:
        fn_name  = PySparkGenerator._to_fn_name(parsed.sp_name) if parsed.sp_name else "run_query"
        call_args = ["spark"]
        for p in parsed.parameters:
            py_nm   = CV._clean_name(p.name)
            default = CV._py_default(p.default) or '"TODO"'
            call_args.append(f"{py_nm}={default}")

        args_str = "".join(f"        {a},\n" for a in call_args)
        return (
            f"# =============================================================================\n"
            f"# ENTRY POINT\n"
            f"# =============================================================================\n"
            f'if __name__ == "__main__":\n'
            f"    # --- run locally or on Databricks --------------------------------\n"
            f"    logger.info(\"Starting PySpark conversion: {fn_name}\")\n"
            f"    result = {fn_name}(\n"
            + args_str
            + f"    )\n"
            f"    logger.info(f\"Result row count: {{result.count()}}\")\n"
            f"    result.printSchema()\n"
            f"    result.show(50, truncate=False)"
        )

    @staticmethod
    def _validation_scaffold(parsed: ParsedSQL) -> str:
        fn_name = PySparkGenerator._to_fn_name(parsed.sp_name) if parsed.sp_name else "run_query"
        deps    = ", ".join(f'"{t}"' for t in parsed.temp_tables) or "# none"
        return (
            f"# =============================================================================\n"
            f"# VALIDATION HELPERS  (run after conversion to verify correctness)\n"
            f"# =============================================================================\n"
            f"def validate_row_count(expected: int, result_df: DataFrame) -> bool:\n"
            f"    actual = result_df.count()\n"
            f"    ok = expected == actual\n"
            f"    logger.info(f\"Row-count check — expected: {{expected}}, got: {{actual}} — {{\"PASS\" if ok else \"FAIL\"}}\")\n"
            f"    return ok\n\n"
            f"def validate_schema(expected_cols: List[str], result_df: DataFrame) -> bool:\n"
            f"    actual_cols = [f.name for f in result_df.schema.fields]\n"
            f"    missing = [c for c in expected_cols if c not in actual_cols]\n"
            f"    if missing:\n"
            f"        logger.warning(f\"Missing columns: {{missing}}\")\n"
            f"    ok = len(missing) == 0\n"
            f"    logger.info(f\"Schema check — {{\"PASS\" if ok else \"FAIL\"}}\")\n"
            f"    return ok\n\n"
            f"def validate_no_nulls(col_name: str, result_df: DataFrame) -> bool:\n"
            f"    null_count = result_df.filter(F.col(col_name).isNull()).count()\n"
            f"    ok = null_count == 0\n"
            f"    logger.info(f\"Null check on '{{col_name}}' — {{null_count}} nulls — {{\"PASS\" if ok else \"FAIL\"}}\")\n"
            f"    return ok"
        )

    @staticmethod
    def _needs_delta(parsed: ParsedSQL) -> bool:
        body = parsed.raw_body.upper()
        return any(k in body for k in ("UPDATE ", "DELETE ", "MERGE ", "TRANSACTION"))
 
    @staticmethod
    def _to_fn_name(sp_name: str) -> str:
        if not sp_name:
            return "run_query"
        # Remove schema prefix (dbo.usp_... ? usp_...)
        name = sp_name.split(".")[-1]
        name = re.sub(r"\W+", "_", name).lower()
        return name
 